### ISSUE TITLE
Add Speaker Decks/Resources

### ISSUE THREAD

**Issue by HarshKapadia2** [OurTechCommunity/meetup#6]
For every MeetUp, we should add links to speaker decks or any other resources that the speakers want to share, if available.

Adding links below the speaker's topic in the 'Event' column of the schedule table would be one place to add the links IMO.

**Comment by HarshKapadia2** [comment]
@tusharnankani can you please add links to speaker decks/resource sites for MeetUp no. 2?

**Comment by HarshKapadia2** [comment]
@tusharnankani any updates on this?

**Comment by tusharnankani** [comment]
Darshan Rander: https://1drv.ms/p/s!Ai1OliGaJWO-4AUoNI29WYkqev8O?e=04LUD0

Tushar Nankani: https://docs.google.com/presentation/d/1-a0FCI-z8pTrmHRq363KG9bxhkuf4zDDr_suuTQe2gg/edit?usp=sharing

**Comment by SirusCodes** [comment]
fixed in #7 

Sorry I forgot to make PR😅
